services:
  db:
    image: postgres:18-alpine
    container_name: liberia-db
    environment:
      POSTGRES_DB: liberia-db
      POSTGRES_USER: liberia-user
      POSTGRES_PASSWORD: liberia-pass
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD SHELL", "pg_isready -U liberia-user -d liberia-db"]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always