

# List available commands
help:
    just --list --unsorted --list-heading $'BOOK-SERVICE\n'

# Run lints (cargo fmt and clippy)
lint:
    cargo +nightly fmt --package book_service -- --check
    cargo clippy --all-targets -- -D warnings

# Run cargo check
check:
    cargo check

# Run cargo build
build:
    cargo build --all-targets

# Run cargo clean on the book_service package
clean:
    cargo clean --package book_service

# Run cargo test
test:
    cargo test

# Run server app
app:
    export $(grep -v '^#' .env | xargs) && \
    cargo run --bin app -r -q

# Run DB migration cli
migration *cmd:
    export $(grep -v "^#" .env | xargs) && \
    DB_HOST="localhost" \
    DATABASE_URL="postgres://liberia-user:liberia-pass@localhost:5432/liberia-db" \
    cargo run --bin migration -- migration {{ cmd }}

# Run docker commands
docker *cmd:
    docker {{ cmd }}


docker-db: 
    docker exec -it liberia-db psql -U liberia-user -d liberia-db

